# Example usage:
# Build:
#   docker buildx build --platform linux/amd64 -f scripts/docker/Dockerfile.amd64 -t nntbn:amd64 . --load
# Run:
#   docker run --rm -it --platform linux/amd64 nntbn:amd64 make test ARCH=generic LDFLAGS="-lm"

# Base
FROM ubuntu:latest as base
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    clang \
    lld

# Build
FROM base as build
COPY . /nn
WORKDIR /nn

ENTRYPOINT []
CMD ["/bin/bash"]
