name: Test

on:
  push:
    branches: ["*"]
    tags-ignore: ["*"]
  pull_request:
    branches: ["*"]

  workflow_dispatch:
    inputs:
      logLevel:
        description: Log Level
        default: info
        type: choice
        options:
          - debug
          - error
          - fatal
          - info
          - panic
          - warning
      environment:
        description: Environment
        default: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init

      - name: Install ARM GCC Toolchain
        run: sudo apt-get install -y gcc-arm-none-eabi

      - name: Run Tests
        run: |
          make test
