name: Test

on:
  push:
    branches: ["*"]
    tags-ignore: ["*"]
  pull_request:
    branches: ["*"]

  workflow_dispatch:
    inputs:
      logLevel:
        description: Log Level
        default: info
        type: choice
        options:
          - debug
          - error
          - fatal
          - info
          - panic
          - warning
      environment:
        description: Environment
        default: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init

      - name: Run Tests
        run: |
          docker buildx build --platform linux/arm64 -f scripts/docker/Dockerfile.arm -t nntbn:arm . --load
          docker run --rm -it --platform linux/arm64 nntbn:arm /nn/build/tests/arch/arm/cmsis/neuron
          docker run --rm -it --platform linux/arm64 nntbn:arm /nn/build/tests/arch/arm/neon/neuron

          docker buildx build --platform linux/amd64 -f scripts/docker/Dockerfile.generic -t nntbn:generic . --load
          docker run --rm -it --platform linux/amd64 nntbn:generic /nn/build/tests/arch/generic/neuron
